language: java
jdk:
  - oraclejdk8
sudo: false
directories:
  -&TEST
before_script:
  - $HOME = '/home/travis/build/Guardryan/ConsoleChess/'

script:
  - gradle test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/